### ISSUE TITLE
Tracking issue for project completeness

### ISSUE THREAD

**Issue by regexident** [regexident/rustfmt-configs-guide#1]
The project's current completeness status:

- [x] `array_layout`
  - [x] `"Block"`
  - [x] `"Visual"`
- [x] `array_width`
- [x] `chain_indent`
  - [x] `"Block"`
  - [x] `"Visual"`
- [x] `chain_one_line_max`
- [x] `closure_block_indent_threshold`
- [x] `comment_width`
- [x] `condense_wildcard_suffices`
  - [x] `true`
  - [x] `false`
- [x] `control_brace_style`
  - [x] `"AlwaysNextLine"`
  - [x] `"AlwaysSameLine"`
  - [x] `"ClosingNextLine"`
- [x] `disable_all_formatting`
  - [x] `true`
  - [x] `false`
- [x] `error_on_line_overflow`
  - [x] `true`
  - [x] `false`
- [x] `fn_args_density`
  - [x] `"Compressed"`
  - [x] `"CompressedIfEmpty"`
  - [x] `"Tall"`
  - [x] `"Vertical"`
- [x] `fn_args_layout`
  - [x] `"Block"`
  - [x] `"Visual"`
- [x] `fn_args_paren_newline`
  - [x] `true`
  - [x] `false`
- [x] `fn_brace_style`
  - [x] `"AlwaysNextLine"`
  - [x] `"PreferSameLine"`
  - [x] `"SameLineWhere"`
- [x] `fn_call_style`
  - [x] `"Block"`
  - [x] `"Visual"`
- [x] `fn_call_width`
- [x] `fn_empty_single_line`
  - [x] `true`
  - [x] `false`
- [x] `fn_return_indent`
  - [x] `"WithArgs"`
  - [x] `"WithWhereClause"`
- [x] `fn_single_line`
  - [x] `true`
  - [x] `false`
- [x] `force_explicit_abi`
  - [x] `true`
  - [x] `false`
- [x] `force_format_strings`
  - [x] `true`
  - [x] `false`
- [x] `format_strings`
  - [x] `true`
  - [x] `false`
- [x] `generics_indent`
  - [x] `"Block"`
  - [x] `"Visual"`
- [x] `generics_style`
  - [x] `"Default"`
  - [x] `"Rfc"`
- [x] `hard_tabs`
  - [x] `true`
  - [x] `false`
- [x] `impl_empty_single_line`
  - [x] `true`
  - [x] `false`
- [x] `indent_match_arms`
  - [x] `true`
  - [x] `false`
- [x] `item_brace_style`
  - [x] `"AlwaysNextLine"`
  - [x] `"PreferSameLine"`
  - [x] `"SameLineWhere"`
- [x] `match_block_trailing_comma`
  - [x] `true`
  - [x] `false`
- [x] `max_width`
- [x] `newline_style`
  - [x] `"Native"`
  - [x] `"Unix"`
  - [x] `"Windows"`
- [x] `normalize_comments`
  - [x] `true`
  - [x] `false`
- [x] `reorder_imported_names`
  - [x] `true`
  - [x] `false`
- [x] `reorder_imports`
  - [x] `true`
  - [x] `false`
- [x] `single_line_if_else_max_width`
- [x] `skip_children`
  - [x] `true`
  - [x] `false`
- [x] `space_after_bound_colon`
  - [x] `true`
  - [x] `false`
- [x] `space_after_type_annotation_colon`
  - [x] `true`
  - [x] `false`
- [x] `space_before_bound`
  - [x] `true`
  - [x] `false`
- [x] `space_before_type_annotation`
  - [x] `true`
  - [x] `false`
- [x] `spaces_around_ranges`
  - [x] `true`
  - [x] `false`
- [x] `spaces_within_angle_brackets`
  - [x] `true`
  - [x] `false`
- [x] `spaces_within_parens`
  - [x] `true`
  - [x] `false`
- [x] `spaces_within_square_brackets`
  - [x] `true`
  - [x] `false`
- [x] `struct_lit_multiline_style`
  - [x] `"ForceMulti"`
  - [x] `"PreferSingle"`
- [x] `struct_lit_style`
  - [x] `"Block"`
  - [x] `"Visual"`
- [x] `struct_lit_width`
- [x] `struct_variant_width`
- [x] `tab_spaces`
  - [x] `2`
  - [x] `4`
- [x] `take_source_hints`
  - [x] `true`
  - [x] `false`
- [x] `trailing_comma`
  - [x] `"Always"`
  - [x] `"Never"`
  - [x] `"Vertical"`
- [x] `type_punctuation_density`
  - [x] `"Compressed"`
  - [x] `"Wide"`
- [x] `use_try_shorthand`
  - [x] `true`
  - [x] `false`
- [x] `where_density`
  - [x] `"Compressed"`
  - [x] `"CompressedIfEmpty"`
  - [x] `"Tall"`
  - [x] `"Vertical"`
- [x] `where_indent`
  - [x] `"Block"`
  - [x] `"Visual"`
- [x] `where_layout`
  - [x] `"Horizontal"`
  - [x] `"HorizontalVertical"`
  - [x] `"Mixed"`
  - [x] `"Vertical"`
- [x] `where_pred_indent`
  - [x] `"Block"`
  - [x] `"Visual"`
- [x] `where_style`
  - [x] `"Default"`
  - [x] `"Rfc"`
- [x] `wrap_comments`
  - [x] `true`
  - [x] `false`
- [x] `wrap_match_arms`
  - [x] `true`
  - [x] `false`
- [x] `write_mode`

**Comment by regexident** [comment]
100% coverage reached. 🍾 🎉
